ProtractedSpeciationProcess:
  incipient_species_extinction_rate:
  speciation_initiation_from_orthospecies_rate:
  speciation_initiation_from_incipient_species_rate:
  speciation_completion_rate:
  orthospecies_extinction_rate:
  aincipient_species_extinction_rate:

generate_sample:
  max_time: 50
  num_extant_orthospecies:
  num_extant_lineages:
  is_retry_on_total_extinction:
  max_retries:

seq-gen:
  state_freqs: [0.4, 0.4, 0.1, 0.1]
  general_rates: [0.8, 0.4, 0.4, 0.2, 0.2, 0.1]
  MODEL:
  SEQUENCE_LENGTH:
  NUMBER_OF_DATASETS:
  NUMBER_OF_PARTITIONS:
  -sSCALE:
  -dSCALE:
  CODON_POSITION_RATES:
  ALPHA:
  NUM_CATEGORIES:
  PROPORTION_INVARIABLE:
  STATE_FREQUENCIES:
  TRANSITION_TRANSVERSION_RATIO:
  RATE_MATRIX_VALUES:
  ANCESTRAL_SEQUENCE_NUMBER:
  RANDOM_NUMBER_SEED:
  op:                                                       # This option selects the format of the output file. The default is PHYLIP format.
  or:                                                       # PHYLIP format.
  on:                                                       # Relaxed PHYLIP format: PHYLIP format expects exactly 10 characters for the name (padded with spaces if the name is actually less than 10). With this option the output file can have up to 256 characters in the name, followed by a single space before the sequence. The longer taxon names are read from the tree. Some programs can read this and it keeps long taxon names.
  of :                                                      # NEXUS format: This creates a NEXUS file which will load into PAUP. It generates one DATA block per dataset. It also includes the simulation settings as comments which will be ignored by PAUP.
  TEXT_FILE_NAME:
  wa:
  wr:
  q:
  h:
